[START]
ru = """
    Привет, это проект от @programistich, за любыми проблемами или идеями обращайтесь к нему же!

    <b>Что умеет этот бот?</b>
    • Следить за деятельностью странички в Twitter
    Для этого отправьте ссылку на Twitter аккаунт или напишите /add %ник_странички_в_твиттере%
    • Отобразить твит в удобном представление телеграмма
    Для этого отправьте ссылку на твит или напишите /get %ссылка_на_твит%
    • Вторичные функции
    /donate - поддержать автора @programistich
    /ping - проверка работает ли бот сейчас
    /help - показать возможности
"""

[HELP]
ru = """
    Возможности бота:
    • Следить за деятельностью странички в Twitter
    Для этого отправьте ссылку на Twitter аккаунт или напишите /add %ник_странички_в_твиттере%
    • Отобразить твит в удобном представление телеграмма
    Для этого отправьте ссылку на твит или напишите /get %ссылка_на_твит%
    • Вторичные функции
    /donate - поддержать автора @programistich
    /ping - проверка работает ли бот сейчас
    /help - показать это сообщение
"""

[PING]
ru = "Бот сейчас работает"

[LIKE]
ru = """
        Лайк <a href="{}">{}</a> на <a href="{}">твит</a> от <a href="{}">{}</a>
"""

[DONATE]
ru = """
        Есть несколько вариантов поддержки:
        • <a href="https://send.monobank.ua/jar/9VVjaU8Pwg">Банка Monobank</a>
        • Карта Monobank <code>4441114440821211</code>
        • Криптовалюта ETH <code>0xf6A2255f333EF47845BaCfD26A0bEaaD296B9019</code>
"""

[NEW_ACCOUNT_GOOD]
ru = """
    Twitter аккаунт {} успешно добавлен в чат
"""

[NEW_ACCOUNT_BAD]
ru = """
    Этот Twitter аккаунт {} уже добавлен в чат
"""

[ERROR]
ru = """
    Что-то пошло не так
"""
