[START]
ru = """
    Привет, это проект TwitterX от @programistich, за любыми проблемами или идеями обращайтесь к нему же!
    <b>Что умеет этот бот?</b>
    • Следить за деятельностью странички в Twitter
    Для этого отправьте ссылку на Twitter аккаунт или напишите /add %ник_странички_в_твиттере%
    • Отобразить твит в удобном представление телеграмма
    Для этого отправьте ссылку на твит или напишите /get %ссылка_на_твит%
    • Вторичные функции
    /donate - поддержать автора @programistich
    /ping - проверка работает ли бот сейчас
    /help - показать возможности

    <i>Для коректной роботы в группе нужно предоставить права администратора</i>
"""

[HELP]
ru = """
    <b>Возможности бота:</b>
    • Следить за деятельностью странички в Twitter
    Для этого отправьте ссылку на Twitter аккаунт или напишите /add %ник_странички_в_твиттере%
    • Отобразить твит в удобном представление телеграмма
    Для этого отправьте ссылку на твит или напишите /get %ссылка_на_твит%
    • Вторичные функции
    /donate - поддержать автора @programistich
    /ping - проверка работает ли бот сейчас
    /help - показать это сообщение

    <i>Для коректной роботы в группе нужно предоставить права администратора</i>
"""

[PING]
ru = "Живой я, живой, чо беспокоишь меня"

[DONATE]
ru = """
        Есть несколько вариантов поддержки:
        • <a href="https://send.monobank.ua/jar/9VVjaU8Pwg">Банка Monobank</a>
        • Карта Monobank <code>4441114440821211</code>
        • Криптовалюта ETH <code>0xf6A2255f333EF47845BaCfD26A0bEaaD296B9019</code>
"""

[ACCOUNT_GOOD]
ru = """
    Twitter аккаунт {} успешно добавлен в чат
"""

[ACCOUNT_EXIST]
ru = """
    Twitter аккаунт {} уже добавлен в чат
"""

[ACCOUNT_NOT_FOUND]
ru = """
    Twitter аккаунт {} не найден
"""

[TWEET_NOT_FOUND]
ru = """
    Этот твит не найден
"""

[LIKE]
ru = """
        Лайк <a href="{}">{}</a> на <a href="{}">твит</a> от <a href="{}">{}</a>
"""

[ERROR]
ru = """
    Что-то пошло не так
"""
